module FT
  CONFIG_OPTION = {
      ENVIRONMENT_PROPERTIES: true,
      SUBPIXEL_RENDERING:     false,
      FORCE_INT64:            false,
      NO_ASSEMBLER:           false,
      INLINE_MULFIX:          true,
      USE_LZW:                true,
      USE_ZLIB:               true,
      SYSTEM_ZLIB:            false,
      USE_BZIP2:              false,
      DISABLE_STREAM_SUPPORT: false,
      USE_PNG:                false,
      USE_HARFBUZZ:           false,
      POSTSCRIPT_NAMES:       true,
      ADOBE_GLYPH_LIST:       true,
      MAC_FONTS:              true,
      INCREMENTAL:            true
  }

  CONFIG_OPTION[:GUESSING_EMBEDDED_RFORK] = CONFIG_OPTION[:MAC_FONTS]

  RENDER_POOL_SIZE = 16384
  MAX_MODULES = 32
  # DEBUG_LEVEL = :ERROR
  # DEBUG_LEVEL = :DEBUG
  DEBUG_AUTOFIT = false
  DEBUG_MEMORY = false

  CONFIG_OPTION[:USE_MODULE_ERRORS] = false
  CONFIG_OPTION[:PIC] = false
  CONFIG_OPTION[:ENVIRONMENT_PROPERTIES] = true
  CONFIG_OPTION[:NO_DEFAULT_SYSTEM] = false

  module TT
    CONFIG_OPTION[:EMBEDDED_BITMAPS] = true
    CONFIG_OPTION[:POSTSCRIPT_NAMES] = true
    CONFIG_OPTION[:SFNT_NAMES] = true
    CMAP = {
        FORMAT_0: true,
        FORMAT_2: true,
        FORMAT_4: true,
        FORMAT_6: true,
        FORMAT_8: true,
        FORMAT_10: true,
        FORMAT_12: true,
        FORMAT_13: true,
        FORMAT_14: true,
    }

    CONFIG_OPTION[:BYTECODE_INTERPRETER] = true
    # CONFIG_OPTION[:SUBPIXEL_HINTING] = 1
    CONFIG_OPTION[:SUBPIXEL_HINTING] = 2
    CONFIG_OPTION[:COMPONENT_OFFSET_SCALED] = true
    CONFIG_OPTION[:GX_VAR_SUPPORT] = true
    CONFIG_OPTION[:BDF] = true
    CONFIG_OPTION[:MAX_RUNNABLE_OPCODES] = 1000000

    USE_BYTECODE_INTERPRETER = CONFIG_OPTION[:BYTECODE_INTERPRETER]
    CONFIG_OPTION[:SUBPIXEL_HINTING_INFINALITY] = CONFIG_OPTION[:SUBPIXEL_HINTING] == 1
    CONFIG_OPTION[:SUBPIXEL_HINTING_MINIMAL] = CONFIG_OPTION[:SUBPIXEL_HINTING] == 2
  end

  module T1
    MAX_DICT_DEPTH = 5
    MAX_SUBRS_CALLS = 16
    MAX_CHARSTRINGS_OPERANDS = 256
    CONFIG_OPTION[:NO_AFM] = false
    CONFIG_OPTION[:NO_MM_SUPPORT] = false
    CONFIG_OPTION[:OLD_ENGINE] = false
  end

  module CFF
    CONFIG_OPTION[:DARKENING_PARAMETER_X1] = 500
    CONFIG_OPTION[:DARKENING_PARAMETER_Y1] = 400

    CONFIG_OPTION[:DARKENING_PARAMETER_X2] = 1000
    CONFIG_OPTION[:DARKENING_PARAMETER_Y2] = 275

    CONFIG_OPTION[:DARKENING_PARAMETER_X3] = 1667
    CONFIG_OPTION[:DARKENING_PARAMETER_Y3] = 275

    CONFIG_OPTION[:DARKENING_PARAMETER_X4] = 2333
    CONFIG_OPTION[:DARKENING_PARAMETER_Y4] = 0

    CONFIG_OPTION[:OLD_ENGINE] = false
  end

  module AF
    CONFIG_OPTION[:CJK] = true
    CONFIG_OPTION[:INDIC] = true
    CONFIG_OPTION[:USE_WARPER] = true
    CONFIG_OPTION[:TT_SIZE_METRICS] = false
  end
end

