module FT
  CONFIG_OPTION = {}

  CONFIG_OPTION[:ENVIRONMENT_PROPERTIES] = true
  CONFIG_OPTION[:SUBPIXEL_RENDERING] = false
  CONFIG_OPTION[:FORCE_INT64] = false
  CONFIG_OPTION[:INLINE_MULFIX] = true
  CONFIG_OPTION[:USE_LZW] = true
  CONFIG_OPTION[:USE_ZLIB] = true
  CONFIG_OPTION[:SYSTEM_ZLIB] = false
  CONFIG_OPTION[:USE_BZIP2] = false
  CONFIG_OPTION[:DISABLE_STREAM_SUPPORT] = false
  CONFIG_OPTION[:USE_PNG] = false
  CONFIG_OPTION[:USE_HARFBUZZ] = false
  CONFIG_OPTION[:POSTSCRIPT_NAMES] = true
  CONFIG_OPTION[:ADOBE_GLYPH_LIST] = true
  CONFIG_OPTION[:MAC_FONTS] = true
  CONFIG_OPTION[:GUESSING_EMBEDDED_RFORK] = CONFIG_OPTION[:MAC_FONTS]
  CONFIG_OPTION[:INCREMENTAL] = true
  CONFIG_OPTION[:USE_MODULE_ERRORS] = false
  CONFIG_OPTION[:PIC] = false
  CONFIG_OPTION[:ENVIRONMENT_PROPERTIES] = true
  CONFIG_OPTION[:NO_DEFAULT_SYSTEM] = false

  RENDER_POOL_SIZE = 16384

  # DEBUG_LEVEL = ERROR
  # DEBUG_LEVEL = DEBUG
  DEBUG_AUTOFIT = false
  DEBUG_MEMORY = false

  module TT
    CONFIG_OPTION[:EMBEDDED_BITMAPS] = true
    CONFIG_OPTION[:POSTSCRIPT_NAMES] = true
    CONFIG_OPTION[:SFNT_NAMES] = true
    CONFIG_OPTION[:BYTECODE_INTERPRETER] = true
    CONFIG_OPTION[:COMPONENT_OFFSET_SCALED] = true
    CONFIG_OPTION[:GX_VAR_SUPPORT] = true
    CONFIG_OPTION[:BDF] = true
    CONFIG_OPTION[:MAX_RUNNABLE_OPCODES] = 1000000
    # CONFIG_OPTION[:SUBPIXEL_HINTING] = 1
    # CONFIG_OPTION[:SUBPIXEL_HINTING] = 2

    USE_BYTECODE_INTERPRETER = CONFIG_OPTION[:BYTECODE_INTERPRETER]
    CONFIG_OPTION[:SUBPIXEL_HINTING_INFINALITY] = CONFIG_OPTION[:SUBPIXEL_HINTING] == 1
    CONFIG_OPTION[:SUBPIXEL_HINTING_MINIMAL] = CONFIG_OPTION[:SUBPIXEL_HINTING] == 2
  end

  module T1
    MAX_DICT_DEPTH = 5
    MAX_SUBRS_CALLS = 16
    MAX_CHARSTRINGS_OPERANDS = 256
    CONFIG_OPTION[:NO_AFM] = false
    CONFIG_OPTION[:NO_MM_SUPPORT] = false
  end

  module CFF
    CONFIG_OPTION[:DARKENING_PARAMETER_X1] = 500
    CONFIG_OPTION[:DARKENING_PARAMETER_Y1] = 400

    CONFIG_OPTION[:DARKENING_PARAMETER_X2] = 1000
    CONFIG_OPTION[:DARKENING_PARAMETER_Y2] = 275

    CONFIG_OPTION[:DARKENING_PARAMETER_X3] = 1667
    CONFIG_OPTION[:DARKENING_PARAMETER_Y3] = 275

    CONFIG_OPTION[:DARKENING_PARAMETER_X4] = 2333
    CONFIG_OPTION[:DARKENING_PARAMETER_Y4] = 0

    CONFIG_OPTION[:OLD_ENGINE] = false
  end

  module AF
    CONFIG_OPTION[:CJK] = true
    CONFIG_OPTION[:INDIC] = true
    CONFIG_OPTION[:USE_WARPER] = true
  end
end

